name: "merapipeline"

on: 
  # workflow_dispatch
  push:
    branches:
    - 'features/**'
    - 'main'


permissions: 
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: merarunner

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v4
    #   with:
    #     terraform_version: 1.6.6

    - name: Azure Login
      uses: Azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      working-directory: environment\prod


    - name: Terraform Diagnostic
      shell: powershell
      working-directory: environment\prod
      run: |
        Write-Host "===== LOCATION ====="
        Get-Location

        Write-Host "===== TERRAFORM COMMAND ====="
        Get-Command terraform | Format-List *

        Write-Host "===== TERRAFORM VERSION ====="
        terraform version

        Write-Host "===== TERRAFORM FILES ====="
        Get-ChildItem -Force

        Write-Host "===== TERRAFORM PLAN ====="
        terraform plan -input=false

        Write-Host "===== EXIT CODE ====="
        Write-Host $LASTEXITCODE

    - name: Terraform Binary Check
      shell: powershell
      working-directory: environment\prod
      run: |
        Write-Host "===== TERRAFORM PATH ====="
        where.exe terraform

        Write-Host "===== FILE INFO ====="
        $tf = Get-Command terraform
        Get-Item $tf.Source | Format-List FullName,Length,LastWriteTime

        Write-Host "===== DIRECT EXECUTION ====="
        & $tf.Source version

        Write-Host "===== EXIT CODE ====="
        Write-Host $LASTEXITCODE


    - name: Terraform Init
      shell: powershell
      run: |
        terraform init -input=false 
      working-directory: environment\prod

    - name: Terraform Validate
      run: terraform validate
      working-directory: environment\prod

    - name: Terraform Plan
      run: terraform plan
      working-directory: environment\prod
      
    - name: Terraform Apply
      shell: powershell
      run: |
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
      working-directory: environment\prod

    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve
    #   working-directory: environment\prod